# Generated by Django 6.0.4 on 2026-04-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='reporter',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('citizen', 'Citizen')], default='citizen', max_length=20),
        ),
    ]
